# The base directory of the images
directory = "/home/alex/test"

# Different categories of images can be specified with a [[category]] entry.
# Valid key arguments are:
# name:         The name of this category (string).
# height:       The height of the image (in pixels). It can either be a
#               integer or an array of two integers, in which case it specifies
#               a range of valid image heights (the second element is
#               interpreted as inclusive).
# width:        The width of the image (in pixels). As above, this can be
#               specified as an array of two integer values.
# min_pixels:   The minimum amount of pixels in the image.
# max_pixels:   The maximum amount of pixels in the image.
#
# Each category needs to have a name to be valid.
# It might be a good idea to have a category which only contains a name tag,
# so it is guaranteed that every image in the base categoryectory satisfies the
# conditions of at least one category.
# Earlier defined categories have precedence.

[[category]]
name = "1080p"
min_height = 1080
max_height = 1200
width = 1920

[[category]]
name = "1440p"
min_height = 1440
max_height = 1600
width = 2560

[[category]]
name = "QHDplus"
height = 1800
width = 3200

[[category]]
name = "UHD"
height = 2160
width = 3840

[[category]]
name = "lowres"
max_pixels = 2073599
max_height = 1080
max_width = 1920

[[category]]
name = "highres"
min_pixels = 8294401
min_height = 2160
min_width = 3840

[[category]]
name = "others"
